spring.application.name=booking-api
spring.config.import=optional:file:.env

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_api
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs

# JWT
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}
jwt.audience=${JWT_AUDIENCE}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

#Host
#FE
app.frontend.urls=${FRONTEND_URLS}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#DevTools
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

#VNPay
vnpay.url=${VNPAY_URL}
vnpay.api=${VNPAY_API}
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.frontend-return-url=${VNPAY_FRONTEND_RETURN_URL}